import type { Metadata } from "next";
import "./globals.css";
import Footer from "../app/client/components/Footer";
import Header from "../app/client/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
   <html lang="en">
      <body>
        <Header />
        <main className=''>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
